#!/usr/bin/python
from pycomm3 import REAL, STRING, DINT

from PF755Driver import PF755Driver

ip = "10.1.77.34"
print(f"Connecting to: {ip}")
drive = PF755Driver(ip)
drive.open()

(drive.read_parameter(0, 25).value)
(drive.read_parameter(0, 26).value)
(drive.read_parameter(0, 27).value)
(drive.read_parameter(0, 28).value)
(drive.read_parameter(0, 29, DINT).value)
(drive.read_parameter(0, 30).value)
(drive.read_parameter(0, 31, DINT).value)
(drive.read_parameter(0, 35).value)
(drive.read_parameter(0, 36).value)
(drive.read_parameter(0, 37).value)
(drive.read_parameter(0, 38).value)
(drive.read_parameter(0, 40, DINT).value)
(drive.read_parameter(0, 43).value)
(drive.read_parameter(0, 44).value)
(drive.read_parameter(0, 60).value)
(drive.read_parameter(0, 61).value)
(drive.read_parameter(0, 62).value)
(drive.read_parameter(0, 63).value)
(drive.read_parameter(0, 70).value)
(drive.read_parameter(0, 75).value)
(drive.read_parameter(0, 100).value)
(drive.read_parameter(0, 150).value)
(drive.read_parameter(0, 155).value)
(drive.read_parameter(0, 156).value)
(drive.read_parameter(0, 163).value)
(drive.read_parameter(0, 220, STRING).value)
(drive.read_parameter(0, 225, STRING).value)
(drive.read_parameter(0, 300, DINT).value)
(drive.read_parameter(0, 301, DINT).value)
(drive.read_parameter(0, 302, DINT).value)
(drive.read_parameter(0, 305, DINT).value)
(drive.read_parameter(0, 306, DINT).value)
(drive.read_parameter(0, 308, DINT).value)
(drive.read_parameter(0, 348, DINT).value)
(drive.read_parameter(0, 349).value)
(drive.read_parameter(0, 356, DINT).value)
(drive.read_parameter(0, 357, DINT).value)
(drive.read_parameter(0, 370, DINT).value)
(drive.read_parameter(0, 372, DINT).value)
(drive.read_parameter(0, 374, DINT).value)
(drive.read_parameter(0, 375).value)
(drive.read_parameter(0, 377, DINT).value)
(drive.read_parameter(0, 378).value)
(drive.read_parameter(0, 388, DINT).value)
(drive.read_parameter(0, 389).value)
(drive.read_parameter(0, 393, DINT).value)
(drive.read_parameter(0, 394).value)
(drive.read_parameter(0, 395).value)
(drive.read_parameter(0, 409, DINT).value)
(drive.read_parameter(0, 410, DINT).value)
(drive.read_parameter(0, 413).value)
(drive.read_parameter(0, 414).value)
(drive.read_parameter(0, 420, DINT).value)
(drive.read_parameter(0, 421, DINT).value)
(drive.read_parameter(0, 422, DINT).value)
(drive.read_parameter(0, 428, DINT).value)
(drive.read_parameter(0, 429).value)
(drive.read_parameter(0, 430).value)
(drive.read_parameter(0, 449, DINT).value)
(drive.read_parameter(0, 450, DINT).value)
(drive.read_parameter(0, 460, DINT).value)
(drive.read_parameter(0, 462, DINT).value)
(drive.read_parameter(0, 463, DINT).value)
(drive.read_parameter(0, 520).value)
(drive.read_parameter(0, 521).value)
(drive.read_parameter(0, 522).value)
(drive.read_parameter(0, 523).value)
(drive.read_parameter(0, 524).value)
(drive.read_parameter(0, 525).value)
(drive.read_parameter(0, 535).value)
(drive.read_parameter(0, 537).value)
(drive.read_parameter(0, 545, DINT).value)
(drive.read_parameter(0, 547).value)
(drive.read_parameter(0, 548).value)
(drive.read_parameter(0, 571, DINT).value)
(drive.read_parameter(0, 621, DINT).value)
(drive.read_parameter(0, 865, DINT).value)
(drive.read_parameter(0, 865, DINT).value)
(drive.read_parameter(0, 865, DINT).value)
(drive.read_parameter(0, 905, DINT).value)
(drive.read_parameter(0, 970, DINT).value)
(drive.read_parameter(0, 974, DINT).value)
(drive.read_parameter(0, 978, DINT).value)

# Port 4 I/O Option Module
# drive.read_parameter(0, 1)
# drive.read_parameter(0, 5)
# drive.read_parameter(0, 6)
# drive.read_parameter(0, 10)
# drive.read_parameter(0, 15)
# drive.read_parameter(0, 20)
# drive.read_parameter(0, 25)
# drive.read_parameter(0, 30)
# drive.read_parameter(0, 35)
# drive.read_parameter(0, 45)
# drive.read_parameter(0, 50)
# drive.read_parameter(0, 51)
# drive.read_parameter(0, 52)
# drive.read_parameter(0, 53)
# drive.read_parameter(0, 55)
# drive.read_parameter(0, 56)
# drive.read_parameter(0, 70)
# drive.read_parameter(0, 71)
# drive.read_parameter(0, 75)
# drive.read_parameter(0, 76)
# drive.read_parameter(0, 78)
# drive.read_parameter(0, 79)
# drive.read_parameter(0, 80)
# drive.read_parameter(0, 81)
# drive.read_parameter(0, 82)

# Port 5 Embedded Ethernet
# drive.read_parameter(0, 17)
# drive.read_parameter(0, 18)
# drive.read_parameter(0, 19)
# drive.read_parameter(0, 20)
# drive.read_parameter(0, 21)
# drive.read_parameter(0, 22)
# drive.read_parameter(0, 23)
# drive.read_parameter(0, 33)
# drive.read_parameter(0, 36)
# drive.read_parameter(0, 38)
# drive.read_parameter(0, 39)
# drive.read_parameter(0, 40)
# drive.read_parameter(0, 41)
# drive.read_parameter(0, 42)
# drive.read_parameter(0, 43)
# drive.read_parameter(0, 44)
# drive.read_parameter(0, 45)
# drive.read_parameter(0, 46)
# drive.read_parameter(0, 47)
# drive.read_parameter(0, 48)
# drive.read_parameter(0, 49)
# drive.read_parameter(0, 50)
# drive.read_parameter(0, 54)


drive.close()


